### PR TITLE
Adding a section for helping Notion users switch to and understand Anytype

### PR DESCRIPTION
**Pull request by jonathan2384**
This adds a new directory in the root of the file system, called `migrating`. The objective for this section is to contain articles and information to help users coming from other knowledge base and note-taking applications to migrate over to Anytype by helping them understand the fundamental differences and demonstrating import options.

My `migrating/notion` section contains information on the fundamental differences (relations, file system, databases) etc that a Notion user would need to understand before moving over to Anytype. I'll come back to this and add a few more sections, such as on the privacy and data ownership advantages that Anytype's sync architecture brings over Notion's, as well as a section or two on the process of importing data from Notion.

Additionally, as Anytype is still in early development, I've added a section on some of Anytype's missing features in comparison to Notion - some of which a Notion user may rely on. My goal is to not alienate prospective Notion migrators, but to help ensure that they will enjoy using the Anytype software by understanding the limitations of it.

### CODE REVIEW

**Comment by d1eselboy** [comment]
@jonathan2384 hey! Thank you for taking such an important theme!
First of all, i love the way you describe things — it's absolutely brilliant!

**Comment by d1eselboy** [comment]
@jonathan2384  
I will merge your changes as they are because 
- I want this section to start helping as soon as possible
- And I don't want to bother you with a ping-pong of changes
- Text part is part very solid and easy to read
- We will wait for adding templates (the place you've finished) in later iterations. 
I will add a few lines there, so it will not break off suddenly. 

What I'm also going to improve:
- I will remake all the images, cause they have low quality and some of them have too much size. Like that: https://github.com/jonathan2384/docs/blob/1/.gitbook/assets/setdemo.png 
- We considered that screenshots should be done with the Default theme turned on, cause components on the Dark one are less visible. Docs sections also have a white background, so the Default screenshot should be better perceived. @jonathan2384,  @div3xi what you are thinking about it? If you are ok with that we need to mention that in CONTRIBUTING.md and change these screenshots later.

**Review by d1eselboy — APPROVED** [review]

**Comment by d1eselboy** [comment]
@jonathan2384 i've made a small recognition for you «This section was initially done by Jonathan» https://doc.anytype.io/d/migrating/start 
Is it ok for you?

**Comment by jonathan2384** [comment]
Yes, that sounds great. However, I'd prefer the attribution to go to my [community.anytype.io](https://community.anytype.io/u/edwards/activity) page, as I'm much more active there compared to my GitHub. Thank you for merging this!

**Pull request merged**
